//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuongTrinhQuanLyKiTucXa
{
    using System;
    using System.Collections.Generic;
    
    public partial class newStudent
    {
        public int id { get; set; }
        public long mobile { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string email { get; set; }
        public string paddress { get; set; }
        public string college { get; set; }
        public string idproof { get; set; }
        public long roomNo { get; set; }
        public string living { get; set; }
    
        public virtual fee fee { get; set; }
        public virtual room room { get; set; }
    }
}
